$('.product-slider').owlCarousel({
    navSpeed:1500,
    dragEndSpeed:1500,
    margin:30,
    responsive:{
        0:{
            items:2
        },
        768:{
            items:3
        }
    }
});